# Generated by Django 4.2.11 on 2026-05-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grasas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
                'db_table': 'COMIDA',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion_dias', models.IntegerField()),
                ('calorias_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'PLAN',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'ROL',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.RESTRICT, to='api.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPlan',
            fields=[
                ('id_usuario_plan', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('completado', 'Completado')], default='activo', max_length=20)),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Plan',
                'verbose_name_plural': 'Usuarios Planes',
                'db_table': 'USUARIO_PLAN',
            },
        ),
        migrations.CreateModel(
            name='PlanComida',
            fields=[
                ('id_plan_comida', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=20)),
                ('id_comida', models.ForeignKey(db_column='id_comida', on_delete=django.db.models.deletion.CASCADE, to='api.comida')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
            options={
                'verbose_name': 'Plan Comida',
                'verbose_name_plural': 'Planes Comidas',
                'db_table': 'PLAN_COMIDA',
            },
        ),
    ]
