# Generated by Django 4.2.11 on 2026-06-02 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def crear_rutinas_iniciales(apps, schema_editor):
    Rutina = apps.get_model('api', 'Rutina')
    Ejercicio = apps.get_model('api', 'Ejercicio')

    rutinas = [
        ('inicio_suave', 'Inicio suave', 'Una rutina breve para empezar a moverse de forma gradual y sostener el habito.', 'mejorar_habitos', 'inicial', 2),
        ('bienestar_general', 'Bienestar general', 'Una propuesta equilibrada para mantener actividad fisica durante la semana.', 'mantener_peso', 'intermedio', 3),
        ('descenso_gradual', 'Descenso gradual', 'Actividad moderada y ejercicios basicos para acompañar un objetivo de descenso de peso.', 'bajar_grasa', 'inicial', 2),
        ('descenso_activo', 'Descenso activo', 'Una rutina de tres dias con actividad aerobica y ejercicios generales.', 'bajar_grasa', 'intermedio', 3),
        ('fuerza_inicial', 'Fuerza inicial', 'Ejercicios basicos para comenzar a desarrollar fuerza de forma progresiva.', 'aumentar_masa', 'inicial', 2),
        ('fuerza_intermedia', 'Fuerza intermedia', 'Una rutina de tres dias para continuar desarrollando fuerza y masa muscular.', 'aumentar_masa', 'intermedio', 3),
    ]

    ejercicios = {
        'inicio_suave': [
            (1, 1, 'Caminata comoda', 'Manten un ritmo que te permita conversar.', None, '', 20),
            (1, 2, 'Movilidad articular', 'Realiza movimientos suaves de hombros, cadera y tobillos.', None, '', 8),
            (2, 1, 'Sentadilla a silla', 'Baja de forma controlada hasta tocar una silla y vuelve a subir.', 2, '10', None),
            (2, 2, 'Flexiones de pared', 'Apoya las manos en una pared y flexiona los brazos.', 2, '8', None),
            (2, 3, 'Puente de gluteos', 'Eleva la cadera con los pies apoyados en el piso.', 2, '10', None),
        ],
        'bienestar_general': [
            (1, 1, 'Caminata activa', 'Manten un ritmo constante y comodo.', None, '', 30),
            (1, 2, 'Movilidad articular', 'Moviliza hombros, cadera y tobillos.', None, '', 8),
            (2, 1, 'Sentadillas', 'Manten la espalda estable y baja de forma controlada.', 3, '12', None),
            (2, 2, 'Flexiones inclinadas', 'Apoya las manos sobre una superficie estable.', 3, '10', None),
            (3, 1, 'Puente de gluteos', 'Eleva la cadera y vuelve a bajar lentamente.', 3, '12', None),
            (3, 2, 'Plancha apoyada', 'Manten el tronco estable con apoyo de antebrazos y rodillas.', 3, '20 segundos', None),
        ],
        'descenso_gradual': [
            (1, 1, 'Caminata activa', 'Manten un ritmo constante sin llegar al agotamiento.', None, '', 25),
            (1, 2, 'Sentadilla a silla', 'Baja de forma controlada hasta tocar una silla.', 2, '10', None),
            (2, 1, 'Caminata por intervalos suaves', 'Alterna dos minutos comodos y un minuto mas activo.', None, '', 25),
            (2, 2, 'Flexiones de pared', 'Flexiona los brazos con las manos apoyadas en una pared.', 2, '10', None),
            (2, 3, 'Puente de gluteos', 'Eleva la cadera con los pies apoyados.', 2, '12', None),
        ],
        'descenso_activo': [
            (1, 1, 'Caminata por intervalos', 'Alterna tres minutos activos y dos minutos comodos.', None, '', 35),
            (1, 2, 'Sentadillas', 'Baja de forma controlada y manten la espalda estable.', 3, '12', None),
            (2, 1, 'Flexiones inclinadas', 'Usa una superficie estable para regular la dificultad.', 3, '10', None),
            (2, 2, 'Zancadas asistidas', 'Usa un apoyo si lo necesitas y alterna ambas piernas.', 3, '10 por pierna', None),
            (3, 1, 'Caminata activa', 'Manten un ritmo constante.', None, '', 35),
            (3, 2, 'Plancha apoyada', 'Manten el tronco estable con el abdomen activo.', 3, '25 segundos', None),
        ],
        'fuerza_inicial': [
            (1, 1, 'Sentadilla a silla', 'Baja de forma controlada y vuelve a subir.', 3, '10', None),
            (1, 2, 'Flexiones inclinadas', 'Usa una superficie estable para regular la dificultad.', 3, '8', None),
            (1, 3, 'Puente de gluteos', 'Eleva la cadera y vuelve a bajar lentamente.', 3, '12', None),
            (2, 1, 'Zancadas asistidas', 'Usa un apoyo si lo necesitas y alterna ambas piernas.', 3, '8 por pierna', None),
            (2, 2, 'Remo con banda', 'Lleva los codos hacia atras con movimiento controlado.', 3, '10', None),
            (2, 3, 'Plancha apoyada', 'Manten el tronco estable con apoyo de rodillas.', 3, '20 segundos', None),
        ],
        'fuerza_intermedia': [
            (1, 1, 'Sentadillas', 'Baja de forma controlada y manten la espalda estable.', 3, '12', None),
            (1, 2, 'Flexiones inclinadas', 'Usa una superficie estable y controla el descenso.', 3, '10', None),
            (2, 1, 'Zancadas asistidas', 'Alterna ambas piernas y conserva la estabilidad.', 3, '10 por pierna', None),
            (2, 2, 'Remo con banda', 'Lleva los codos hacia atras con movimiento controlado.', 3, '12', None),
            (3, 1, 'Puente de gluteos', 'Eleva la cadera y desciende lentamente.', 3, '15', None),
            (3, 2, 'Plancha frontal', 'Manten el tronco estable y evita arquear la espalda.', 3, '30 segundos', None),
        ],
    }

    for codigo, nombre, descripcion, objetivo, nivel, dias_por_semana in rutinas:
        rutina, _ = Rutina.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'descripcion': descripcion,
                'objetivo': objetivo,
                'nivel': nivel,
                'dias_por_semana': dias_por_semana,
                'duracion_semanas': 4,
                'activa': True,
            },
        )
        for dia, orden, nombre_ejercicio, descripcion_ejercicio, series, repeticiones, duracion in ejercicios[codigo]:
            Ejercicio.objects.update_or_create(
                id_rutina=rutina,
                dia=dia,
                orden=orden,
                defaults={
                    'nombre': nombre_ejercicio,
                    'descripcion': descripcion_ejercicio,
                    'series': series,
                    'repeticiones': repeticiones,
                    'duracion_minutos': duracion,
                },
            )


def eliminar_rutinas_iniciales(apps, schema_editor):
    Rutina = apps.get_model('api', 'Rutina')
    UsuarioRutina = apps.get_model('api', 'UsuarioRutina')
    codigos = [
        'inicio_suave',
        'bienestar_general',
        'descenso_gradual',
        'descenso_activo',
        'fuerza_inicial',
        'fuerza_intermedia',
    ]
    UsuarioRutina.objects.filter(id_rutina__codigo__in=codigos).delete()
    Rutina.objects.filter(codigo__in=codigos).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plan_template_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.PositiveSmallIntegerField()),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('series', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('repeticiones', models.CharField(blank=True, max_length=30)),
                ('duracion_minutos', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'db_table': 'EJERCICIO',
                'ordering': ['dia', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivo', models.CharField(choices=[('bajar_grasa', 'Bajar grasa corporal'), ('aumentar_masa', 'Aumentar masa muscular'), ('mantener_peso', 'Mantener peso'), ('mejorar_habitos', 'Mejorar habitos saludables')], max_length=30)),
                ('nivel', models.CharField(choices=[('inicial', 'Inicial'), ('intermedio', 'Intermedio')], max_length=20)),
                ('dias_por_semana', models.PositiveSmallIntegerField()),
                ('duracion_semanas', models.PositiveSmallIntegerField(default=4)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'db_table': 'RUTINA',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRutina',
            fields=[
                ('id_usuario_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_asignacion', models.DateTimeField(auto_now=True)),
                ('id_rutina', models.ForeignKey(db_column='id_rutina', on_delete=django.db.models.deletion.PROTECT, to='api.rutina')),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='rutina_asignada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario rutina',
                'verbose_name_plural': 'Usuarios rutinas',
                'db_table': 'USUARIO_RUTINA',
            },
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id_registro_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('id_ejercicio', models.ForeignKey(db_column='id_ejercicio', on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de ejercicio',
                'verbose_name_plural': 'Registros de ejercicios',
                'db_table': 'REGISTRO_EJERCICIO',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.PositiveSmallIntegerField()),
                ('peso_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_cm', models.PositiveSmallIntegerField()),
                ('peso_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('objetivo', models.CharField(choices=[('bajar_grasa', 'Bajar grasa corporal'), ('aumentar_masa', 'Aumentar masa muscular'), ('mantener_peso', 'Mantener peso'), ('mejorar_habitos', 'Mejorar habitos saludables')], max_length=30)),
                ('actividad', models.CharField(choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], max_length=20)),
                ('preferencia', models.CharField(choices=[('sin_preferencia', 'Sin preferencia'), ('vegetariana', 'Vegetariana'), ('alta_proteina', 'Alta en proteinas'), ('baja_calorias', 'Baja en calorias')], max_length=30)),
                ('dias_entrenamiento', models.PositiveSmallIntegerField(default=3)),
                ('limitaciones', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'db_table': 'PERFIL_USUARIO',
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='id_rutina',
            field=models.ForeignKey(db_column='id_rutina', on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='api.rutina'),
        ),
        migrations.AddConstraint(
            model_name='registroejercicio',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'id_ejercicio', 'fecha'), name='registro_ejercicio_unico_por_dia'),
        ),
        migrations.RunPython(crear_rutinas_iniciales, eliminar_rutinas_iniciales),
    ]
