# Generated by Django 4.2.11 on 2026-06-02 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def preparar_plantillas_alimenticias(apps, schema_editor):
    Plan = apps.get_model('api', 'Plan')
    Comida = apps.get_model('api', 'Comida')
    PlanComida = apps.get_model('api', 'PlanComida')

    Plan.objects.filter(objetivo='bajar_peso').update(objetivo='bajar_grasa')
    Plan.objects.filter(objetivo='subir_peso').update(objetivo='aumentar_masa')
    Plan.objects.filter(objetivo='aumentar_masa_muscular').update(objetivo='aumentar_masa')
    Plan.objects.filter(nivel_actividad='baja').update(nivel_actividad='bajo')
    Plan.objects.filter(nivel_actividad='moderada').update(nivel_actividad='moderado')
    Plan.objects.filter(nivel_actividad='alta').update(nivel_actividad='alto')

    comidas = [
        ('Yogur natural con avena y fruta', 'preparacion', '1 bol', 340, 15, 52, 8),
        ('Tostadas integrales con queso y fruta', 'preparacion', '2 tostadas y 1 fruta', 360, 16, 52, 10),
        ('Avena con banana y nueces', 'preparacion', '1 bol', 410, 12, 61, 15),
        ('Omelette con tostadas integrales', 'preparacion', '2 huevos y 2 tostadas', 420, 24, 38, 18),
        ('Pollo con arroz integral y verduras', 'preparacion', '1 plato', 610, 42, 66, 18),
        ('Pasta integral con pollo y verduras', 'preparacion', '1 plato', 690, 45, 84, 18),
        ('Pescado con papa y verduras', 'preparacion', '1 plato', 560, 38, 54, 17),
        ('Tortilla de verduras con ensalada', 'preparacion', '1 plato', 430, 24, 32, 22),
        ('Ensalada completa con huevo y garbanzos', 'preparacion', '1 plato', 520, 25, 58, 21),
        ('Lentejas con arroz y verduras', 'preparacion', '1 plato', 570, 24, 88, 12),
        ('Tofu con arroz integral y verduras', 'preparacion', '1 plato', 590, 29, 71, 22),
        ('Pasta integral con lentejas y verduras', 'preparacion', '1 plato', 650, 28, 99, 14),
        ('Fruta con nueces', 'grasas_saludables', '1 fruta y 1 punado pequeno', 220, 5, 28, 12),
        ('Yogur natural con semillas', 'lacteos', '1 pote y 1 cucharada', 190, 11, 20, 8),
        ('Tostadas integrales con hummus', 'preparacion', '2 tostadas', 290, 10, 46, 9),
        ('Licuado de yogur, banana y avena', 'preparacion', '1 vaso grande', 430, 19, 68, 10),
    ]
    comidas_creadas = {}
    for nombre, categoria, porcion, calorias, proteinas, carbohidratos, grasas in comidas:
        comida, _ = Comida.objects.update_or_create(
            nombre=nombre,
            defaults={
                'categoria': categoria,
                'porcion_referencia': porcion,
                'calorias': calorias,
                'proteinas': proteinas,
                'carbohidratos': carbohidratos,
                'grasas': grasas,
            },
        )
        comidas_creadas[nombre] = comida

    menu_equilibrado = [
        (1, 1, 'desayuno', 'Yogur natural con avena y fruta', '1 bol', 'Tostadas integrales con queso y fruta'),
        (1, 2, 'almuerzo', 'Pollo con arroz integral y verduras', '1 plato', 'Pescado con papa y verduras'),
        (1, 3, 'merienda', 'Fruta con nueces', '1 porcion', 'Yogur natural con semillas'),
        (1, 4, 'cena', 'Tortilla de verduras con ensalada', '1 plato', 'Ensalada completa con huevo y garbanzos'),
        (2, 1, 'desayuno', 'Avena con banana y nueces', '1 bol', 'Yogur natural con avena y fruta'),
        (2, 2, 'almuerzo', 'Lentejas con arroz y verduras', '1 plato', 'Pollo con arroz integral y verduras'),
        (2, 3, 'merienda', 'Tostadas integrales con queso y fruta', '1 porcion', 'Fruta con nueces'),
        (2, 4, 'cena', 'Pescado con papa y verduras', '1 plato', 'Tortilla de verduras con ensalada'),
        (3, 1, 'desayuno', 'Tostadas integrales con queso y fruta', '1 porcion', 'Avena con banana y nueces'),
        (3, 2, 'almuerzo', 'Pasta integral con pollo y verduras', '1 plato', 'Lentejas con arroz y verduras'),
        (3, 3, 'merienda', 'Yogur natural con semillas', '1 porcion', 'Fruta con nueces'),
        (3, 4, 'cena', 'Ensalada completa con huevo y garbanzos', '1 plato', 'Tortilla de verduras con ensalada'),
    ]
    menu_vegetariano = [
        (1, 1, 'desayuno', 'Yogur natural con avena y fruta', '1 bol', 'Avena con banana y nueces'),
        (1, 2, 'almuerzo', 'Lentejas con arroz y verduras', '1 plato', 'Tofu con arroz integral y verduras'),
        (1, 3, 'merienda', 'Tostadas integrales con hummus', '2 tostadas', 'Fruta con nueces'),
        (1, 4, 'cena', 'Tortilla de verduras con ensalada', '1 plato', 'Ensalada completa con huevo y garbanzos'),
        (2, 1, 'desayuno', 'Avena con banana y nueces', '1 bol', 'Yogur natural con avena y fruta'),
        (2, 2, 'almuerzo', 'Tofu con arroz integral y verduras', '1 plato', 'Lentejas con arroz y verduras'),
        (2, 3, 'merienda', 'Yogur natural con semillas', '1 porcion', 'Tostadas integrales con hummus'),
        (2, 4, 'cena', 'Ensalada completa con huevo y garbanzos', '1 plato', 'Tortilla de verduras con ensalada'),
        (3, 1, 'desayuno', 'Tostadas integrales con queso y fruta', '1 porcion', 'Avena con banana y nueces'),
        (3, 2, 'almuerzo', 'Pasta integral con lentejas y verduras', '1 plato', 'Tofu con arroz integral y verduras'),
        (3, 3, 'merienda', 'Fruta con nueces', '1 porcion', 'Yogur natural con semillas'),
        (3, 4, 'cena', 'Tortilla de verduras con ensalada', '1 plato', 'Ensalada completa con huevo y garbanzos'),
    ]
    menu_fuerza = [
        (1, 1, 'desayuno', 'Omelette con tostadas integrales', '1 porcion', 'Yogur natural con avena y fruta'),
        (1, 2, 'almuerzo', 'Pasta integral con pollo y verduras', '1 plato abundante', 'Pollo con arroz integral y verduras'),
        (1, 3, 'merienda', 'Licuado de yogur, banana y avena', '1 vaso grande', 'Yogur natural con avena y fruta'),
        (1, 4, 'cena', 'Pollo con arroz integral y verduras', '1 plato', 'Pescado con papa y verduras'),
        (2, 1, 'desayuno', 'Yogur natural con avena y fruta', '1 bol abundante', 'Omelette con tostadas integrales'),
        (2, 2, 'almuerzo', 'Pollo con arroz integral y verduras', '1 plato abundante', 'Pasta integral con pollo y verduras'),
        (2, 3, 'merienda', 'Tostadas integrales con queso y fruta', '1 porcion', 'Licuado de yogur, banana y avena'),
        (2, 4, 'cena', 'Pescado con papa y verduras', '1 plato', 'Tortilla de verduras con ensalada'),
        (3, 1, 'desayuno', 'Avena con banana y nueces', '1 bol abundante', 'Omelette con tostadas integrales'),
        (3, 2, 'almuerzo', 'Pasta integral con pollo y verduras', '1 plato abundante', 'Pollo con arroz integral y verduras'),
        (3, 3, 'merienda', 'Licuado de yogur, banana y avena', '1 vaso grande', 'Fruta con nueces'),
        (3, 4, 'cena', 'Ensalada completa con huevo y garbanzos', '1 plato abundante', 'Pollo con arroz integral y verduras'),
    ]
    menu_fuerza_vegetariano = [
        (1, 1, 'desayuno', 'Omelette con tostadas integrales', '1 porcion', 'Yogur natural con avena y fruta'),
        (1, 2, 'almuerzo', 'Pasta integral con lentejas y verduras', '1 plato abundante', 'Tofu con arroz integral y verduras'),
        (1, 3, 'merienda', 'Licuado de yogur, banana y avena', '1 vaso grande', 'Tostadas integrales con hummus'),
        (1, 4, 'cena', 'Tofu con arroz integral y verduras', '1 plato', 'Ensalada completa con huevo y garbanzos'),
        (2, 1, 'desayuno', 'Yogur natural con avena y fruta', '1 bol abundante', 'Avena con banana y nueces'),
        (2, 2, 'almuerzo', 'Lentejas con arroz y verduras', '1 plato abundante', 'Pasta integral con lentejas y verduras'),
        (2, 3, 'merienda', 'Tostadas integrales con hummus', '2 tostadas', 'Yogur natural con semillas'),
        (2, 4, 'cena', 'Tortilla de verduras con ensalada', '1 plato', 'Tofu con arroz integral y verduras'),
        (3, 1, 'desayuno', 'Avena con banana y nueces', '1 bol abundante', 'Omelette con tostadas integrales'),
        (3, 2, 'almuerzo', 'Tofu con arroz integral y verduras', '1 plato abundante', 'Lentejas con arroz y verduras'),
        (3, 3, 'merienda', 'Licuado de yogur, banana y avena', '1 vaso grande', 'Fruta con nueces'),
        (3, 4, 'cena', 'Ensalada completa con huevo y garbanzos', '1 plato abundante', 'Tortilla de verduras con ensalada'),
    ]

    plantillas = [
        ('habitos_equilibrados', 'Habitos equilibrados', 'Ciclo orientativo de tres dias para sostener variedad, alimentos frescos y organizacion cotidiana.', 14, 2000, 'mejorar_habitos', 'moderado', 'todas', menu_equilibrado),
        ('habitos_equilibrados_vegetariano', 'Habitos equilibrados vegetarianos', 'Ciclo orientativo vegetariano de tres dias con legumbres, cereales, frutas y verduras.', 14, 2000, 'mejorar_habitos', 'moderado', 'vegetariana', menu_vegetariano),
        ('descenso_equilibrado', 'Descenso equilibrado', 'Ciclo orientativo de tres dias para acompanar un objetivo gradual de descenso de grasa corporal.', 14, 1800, 'bajar_grasa', 'moderado', 'todas', menu_equilibrado),
        ('descenso_equilibrado_vegetariano', 'Descenso equilibrado vegetariano', 'Ciclo orientativo vegetariano para acompanar un objetivo gradual de descenso de grasa corporal.', 14, 1800, 'bajar_grasa', 'moderado', 'vegetariana', menu_vegetariano),
        ('apoyo_fuerza', 'Apoyo para fuerza', 'Ciclo orientativo de tres dias con comidas completas para acompanar entrenamiento de fuerza.', 14, 2400, 'aumentar_masa', 'alto', 'todas', menu_fuerza),
        ('apoyo_fuerza_vegetariano', 'Apoyo para fuerza vegetariano', 'Ciclo orientativo vegetariano de tres dias para acompanar entrenamiento de fuerza.', 14, 2400, 'aumentar_masa', 'alto', 'vegetariana', menu_fuerza_vegetariano),
    ]

    for codigo, nombre, descripcion, duracion, calorias, objetivo, actividad, preferencia, menu in plantillas:
        plan, _ = Plan.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nombre_plan': nombre,
                'descripcion': descripcion,
                'duracion_dias': duracion,
                'calorias_objetivo': calorias,
                'objetivo': objetivo,
                'nivel_actividad': actividad,
                'preferencia_compatible': preferencia,
                'observaciones': 'Plantilla educativa y orientativa. Adaptar antes de una asignacion profesional.',
                'activo': True,
            },
        )
        for dia, orden, tipo, nombre_comida, porcion, alternativa in menu:
            PlanComida.objects.update_or_create(
                id_plan=plan,
                dia=dia,
                orden=orden,
                defaults={
                    'id_comida': comidas_creadas[nombre_comida],
                    'tipo_comida': tipo,
                    'porcion': porcion,
                    'alternativa': alternativa,
                },
            )


def eliminar_plantillas_alimenticias(apps, schema_editor):
    Plan = apps.get_model('api', 'Plan')
    Comida = apps.get_model('api', 'Comida')
    codigos = [
        'habitos_equilibrados',
        'habitos_equilibrados_vegetariano',
        'descenso_equilibrado',
        'descenso_equilibrado_vegetariano',
        'apoyo_fuerza',
        'apoyo_fuerza_vegetariano',
    ]
    nombres_comidas = [
        'Yogur natural con avena y fruta',
        'Tostadas integrales con queso y fruta',
        'Avena con banana y nueces',
        'Omelette con tostadas integrales',
        'Pollo con arroz integral y verduras',
        'Pasta integral con pollo y verduras',
        'Pescado con papa y verduras',
        'Tortilla de verduras con ensalada',
        'Ensalada completa con huevo y garbanzos',
        'Lentejas con arroz y verduras',
        'Tofu con arroz integral y verduras',
        'Pasta integral con lentejas y verduras',
        'Fruta con nueces',
        'Yogur natural con semillas',
        'Tostadas integrales con hummus',
        'Licuado de yogur, banana y avena',
    ]
    Plan.objects.filter(codigo__in=codigos).delete()
    Comida.objects.filter(nombre__in=nombres_comidas, plancomida__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ejercicio_rutina_usuariorutina_registroejercicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancomida',
            options={'ordering': ['dia', 'orden'], 'verbose_name': 'Plan Comida', 'verbose_name_plural': 'Planes Comidas'},
        ),
        migrations.AddField(
            model_name='comida',
            name='categoria',
            field=models.CharField(choices=[('frutas_verduras', 'Frutas y verduras'), ('cereales_legumbres', 'Cereales y legumbres'), ('proteinas', 'Proteinas'), ('lacteos', 'Lacteos'), ('grasas_saludables', 'Grasas saludables'), ('preparacion', 'Preparacion completa')], default='preparacion', max_length=30),
        ),
        migrations.AddField(
            model_name='comida',
            name='porcion_referencia',
            field=models.CharField(default='1 porcion', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='consideraciones_alimentarias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='codigo',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='preferencia_compatible',
            field=models.CharField(choices=[('todas', 'Todas'), ('vegetariana', 'Vegetariana'), ('alta_proteina', 'Alta en proteinas'), ('baja_calorias', 'Baja en calorias')], default='todas', max_length=30),
        ),
        migrations.AddField(
            model_name='plancomida',
            name='alternativa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plancomida',
            name='dia',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plancomida',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plancomida',
            name='porcion',
            field=models.CharField(default='1 porcion', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarioplan',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuarioplan',
            name='origen',
            field=models.CharField(choices=[('orientativo', 'Orientativo'), ('profesional', 'Profesional')], default='profesional', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nivel_actividad',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], default='moderado', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='objetivo',
            field=models.CharField(choices=[('bajar_grasa', 'Bajar grasa corporal'), ('mantener_peso', 'Mantener peso'), ('aumentar_masa', 'Aumentar masa muscular'), ('mejorar_habitos', 'Mejorar habitos saludables')], default='mantener_peso', max_length=30),
        ),
        migrations.AlterField(
            model_name='plancomida',
            name='id_plan',
            field=models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, related_name='comidas_plan', to='api.plan'),
        ),
        migrations.CreateModel(
            name='RegistroComidaPlan',
            fields=[
                ('id_registro_comida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('id_plan_comida', models.ForeignKey(db_column='id_plan_comida', on_delete=django.db.models.deletion.CASCADE, to='api.plancomida')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de comida del plan',
                'verbose_name_plural': 'Registros de comidas del plan',
                'db_table': 'REGISTRO_COMIDA_PLAN',
            },
        ),
        migrations.AddConstraint(
            model_name='registrocomidaplan',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'id_plan_comida', 'fecha'), name='registro_comida_plan_unico_por_dia'),
        ),
        migrations.RunPython(preparar_plantillas_alimenticias, eliminar_plantillas_alimenticias),
    ]
