# Generated by Django 4.2.11 on 2026-06-02 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_plancomida_options_comida_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=1),
        ),
        migrations.CreateModel(
            name='HistorialPeso',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='historial_peso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de peso',
                'verbose_name_plural': 'Historiales de peso',
                'db_table': 'HISTORIAL_PESO',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='historialpeso',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'fecha'), name='peso_unico_por_dia'),
        ),
    ]
